import Link from 'next/link'

export default function Home() {
  return (
      <main className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
            <div className="max-w-6xl mx-auto px-4 py-16">
                    <div className="text-center mb-16">
                              <div className="text-6xl mb-4">🎓</div>
                                        <h1 className="text-5xl font-bold text-blue-900 mb-4">Planeprof</h1>
                                                  <p className="text-xl text-gray-600 mb-2">
                                                              Planejamento de Aulas baseado na BNCC
                                                                        </p>
                                                                                  <p className="text-gray-500 mb-8">Para Educação Infantil e Ensino Fundamental</p>
                                                                                            <div className="flex gap-4 justify-center flex-wrap">
                                                                                                        <Link
                                                                                                                      href="/planejamento/novo"
                                                                                                                                    className="bg-blue-600 text-white px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-700 transition"
                                                                                                                                                >
                                                                                                                                                              🚀 Criar Planejamento Grátis
                                                                                                                                                                          </Link>
                                                                                                                                                                                      <Link
                                                                                                                                                                                                    href="/biblioteca"
                                                                                                                                                                                                                  className="border-2 border-blue-600 text-blue-600 px-8 py-3 rounded-lg text-lg font-semibold hover:bg-blue-50 transition"
                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                            📚 Ver Biblioteca
                                                                                                                                                                                                                                                        </Link>
                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                  <div className="text-center bg-gradient-to-r from-blue-600 to-blue-700 text-white p-8 rounded-2xl mb-16">
                                                                                                                                                                                                                                                                                            <div className="text-4xl mb-3">🎁</div>
                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold mb-2">Crie e visualize grátis!</h2>
                                                                                                                                                                                                                                                                                                                <p className="text-blue-100 mb-6">
                                                                                                                                                                                                                                                                                                                            Gere seu plano de aula com IA, visualize completo e baixe quando quiser.<br/>
                                                                                                                                                                                                                                                                                                                                        Não perca seu tempo com planejamentos... nós fazemos tudo pra você!
                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                            <Link
                                                                                                                                                                                                                                                                                                                                                                        href="/planejamento/novo"
                                                                                                                                                                                                                                                                                                                                                                                    className="bg-white text-blue-600 px-8 py-3 rounded-lg text-lg font-bold hover:bg-blue-50 transition inline-block"
                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                          Começar Agora — É Grátis
                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid md:grid-cols-3 gap-6 mb-16">
                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-3xl mb-3">📋</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-bold text-gray-800 mb-2">Baseado na BNCC</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-500 text-sm">Habilidades e objetivos alinhados à Base Nacional Comum Curricular</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-3xl mb-3">🤖</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h3 className="font-bold text-gray-800 mb-2">Gerado por IA</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-500 text-sm">Planos completos com desenvolvimento, conclusão, dinâmica e PDI</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-3xl mb-3">💰</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="font-bold text-gray-800 mb-2">Assinatura simples</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-500 text-sm">R$ 9,90/mês ou R$ 100,00/ano via Pix. Cancele quando quiser.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <footer className="text-center text-gray-500 text-sm">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p>Desenvolvido com ❤️ para educadores brasileiros</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="mt-1">Contato: dicatop0001@gmail.com</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }